{{- if .Values.service.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.statefulSet.name }}-lb
spec:
  type: NodePort
  selector:
    app: {{ .Values.statefulSet.name }}
  ports:
  - port: {{ .Values.service.nodePort.ports.port }}
    targetPort: {{ .Values.service.nodePort.ports.targetPort }}
{{- end }}
