apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  labels:
    app: redis-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - "redis-server"
        args: {{ toYaml .Values.deployment.args | nindent 10 }}
        ports:
        - containerPort: 6379
        resources: {{ toYaml .Values.resources | nindent 10 }}
