apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-app
spec:
  selector:
    app: redis-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 6379
  type: {{ .Values.service.type }}
