apiVersion: v1
kind: ConfigMap
metadata:
  name: config-configmap
data:
  config_url: "{{ .Values.configMaps.config.config_url }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-configmap
data:
  eureka_service_address: "{{ .Values.configMaps.eureka.eureka_service_address }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  hostname: "mysql-0.mysql"

