apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
  labels:
    app: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}